version: '3'

services:

  api:
    image: earnup/api:latest
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_DATABASE=earnup
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_DATABASE=earnup
    ports:
      - "3308:3306"
    volumes:
      - earnup-mysql-db:/var/lib/mysql

volumes:
  earnup-mysql-db: